# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    # 실행 환경 지정
    runs-on: [self-hosted, notify]

    steps:
#    - name: chown notify
#      run: "sudo chown -Rf notify: /home/ubuntu/actions-runner/_work/notify"

    # Task의 sequence를 명시한다.
    - uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Make gradlew executable
      run: chmod +x /home/ubuntu/actions-runner/_work/notify/notify/gradlew

    - name: Build with Gradle
      run: /home/ubuntu/actions-runner/_work/notify/notify/gradlew clean build -x check

#    - name: backup
#      run: mv /home/ubuntu/notify/notify-0.0.1-master.jar /home/ubuntu/notify/bak/notify-0.0.1-SNAPSHOT.jar_$(date '+%Y%m%d-%H%M%S')

    - name: deploy
      run: mv /home/ubuntu/actions-runner/_work/notify/notify/build/libs/notify-0.0.1-SNAPSHOT.jar /home/ubuntu/notify/notify-0.0.1-master.jar